# coding=utf-8
"""
品种配置文件
支持股指期货和商品期货的各种参数配置
"""

# 品种配置字典
INSTRUMENTS = {
    # ========== 股指期货 (CFFEX) ==========
    "IF": {
        "name": "沪深300股指",
        "exchange": "CFFEX",
        "multiplier": 300,
        "price_tick": 0.2,
        "margin_rate": 0.12,
        "commission_rate": 0.000023,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },
    "IH": {
        "name": "上证50股指",
        "exchange": "CFFEX",
        "multiplier": 300,
        "price_tick": 0.2,
        "margin_rate": 0.12,
        "commission_rate": 0.000023,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },
    "IC": {
        "name": "中证500股指",
        "exchange": "CFFEX",
        "multiplier": 200,
        "price_tick": 0.2,
        "margin_rate": 0.14,
        "commission_rate": 0.000023,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },
    "IM": {
        "name": "中证1000股指",
        "exchange": "CFFEX",
        "multiplier": 200,
        "price_tick": 0.2,
        "margin_rate": 0.15,
        "commission_rate": 0.000023,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },

    # ========== 国债期货 (CFFEX) ==========
    "T": {
        "name": "10年期国债",
        "exchange": "CFFEX",
        "multiplier": 10000,
        "price_tick": 0.005,
        "margin_rate": 0.02,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },
    "TF": {
        "name": "5年期国债",
        "exchange": "CFFEX",
        "multiplier": 10000,
        "price_tick": 0.005,
        "margin_rate": 0.012,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },
    "TS": {
        "name": "2年期国债",
        "exchange": "CFFEX",
        "multiplier": 20000,
        "price_tick": 0.005,
        "margin_rate": 0.005,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },
    "TL": {
        "name": "30年期国债",
        "exchange": "CFFEX",
        "multiplier": 10000,
        "price_tick": 0.01,
        "margin_rate": 0.035,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },

    # ========== 贵金属 (SHFE) ==========
    "AU": {
        "name": "黄金",
        "exchange": "SHFE",
        "multiplier": 1000,
        "price_tick": 0.02,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 10,
        "night_trade": True,
        "currency": "CNY",
    },
    "AG": {
        "name": "白银",
        "exchange": "SHFE",
        "multiplier": 15,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0.00005,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 有色金属 (SHFE) ==========
    "CU": {
        "name": "沪铜",
        "exchange": "SHFE",
        "multiplier": 5,
        "price_tick": 10,
        "margin_rate": 0.10,
        "commission_rate": 0.00005,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "AL": {
        "name": "沪铝",
        "exchange": "SHFE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "ZN": {
        "name": "沪锌",
        "exchange": "SHFE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "PB": {
        "name": "沪铅",
        "exchange": "SHFE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "NI": {
        "name": "沪镍",
        "exchange": "SHFE",
        "multiplier": 1,
        "price_tick": 10,
        "margin_rate": 0.12,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "SN": {
        "name": "沪锡",
        "exchange": "SHFE",
        "multiplier": 1,
        "price_tick": 10,
        "margin_rate": 0.12,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "SS": {
        "name": "不锈钢",
        "exchange": "SHFE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2,
        "night_trade": True,
        "currency": "CNY",
    },
    "AO": {
        "name": "氧化铝",
        "exchange": "SHFE",
        "multiplier": 20,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 黑色系 ==========
    "RB": {
        "name": "螺纹钢",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "HC": {
        "name": "热卷",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "WR": {
        "name": "线材",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },
    "I": {
        "name": "铁矿石",
        "exchange": "DCE",
        "multiplier": 100,
        "price_tick": 0.5,
        "margin_rate": 0.12,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "J": {
        "name": "焦炭",
        "exchange": "DCE",
        "multiplier": 100,
        "price_tick": 0.5,
        "margin_rate": 0.12,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "JM": {
        "name": "焦煤",
        "exchange": "DCE",
        "multiplier": 60,
        "price_tick": 0.5,
        "margin_rate": 0.12,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "SF": {
        "name": "硅铁",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 2,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "SM": {
        "name": "锰硅",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 2,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 能源 ==========
    "SC": {
        "name": "原油",
        "exchange": "INE",
        "multiplier": 1000,
        "price_tick": 0.1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 20,
        "night_trade": True,
        "currency": "CNY",
    },
    "FU": {
        "name": "燃油",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0.00005,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
    "LU": {
        "name": "低硫燃油",
        "exchange": "INE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "BU": {
        "name": "沥青",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0.0001,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 化工 ==========
    "L": {
        "name": "塑料LLDPE",
        "exchange": "DCE",
        "multiplier": 5,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1,
        "night_trade": True,
        "currency": "CNY",
    },
    "V": {
        "name": "PVC",
        "exchange": "DCE",
        "multiplier": 5,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1,
        "night_trade": True,
        "currency": "CNY",
    },
    "PP": {
        "name": "聚丙烯",
        "exchange": "DCE",
        "multiplier": 5,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1,
        "night_trade": True,
        "currency": "CNY",
    },
    "EG": {
        "name": "乙二醇",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "EB": {
        "name": "苯乙烯",
        "exchange": "DCE",
        "multiplier": 5,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "PG": {
        "name": "LPG",
        "exchange": "DCE",
        "multiplier": 20,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 6,
        "night_trade": True,
        "currency": "CNY",
    },
    "TA": {
        "name": "PTA",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 2,
        "margin_rate": 0.07,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "MA": {
        "name": "甲醇",
        "exchange": "CZCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2,
        "night_trade": True,
        "currency": "CNY",
    },
    "SA": {
        "name": "纯碱",
        "exchange": "CZCE",
        "multiplier": 20,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 3.5,
        "night_trade": True,
        "currency": "CNY",
    },
    "FG": {
        "name": "玻璃",
        "exchange": "CZCE",
        "multiplier": 20,
        "price_tick": 1,
        "margin_rate": 0.09,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "UR": {
        "name": "尿素",
        "exchange": "CZCE",
        "multiplier": 20,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 5,
        "night_trade": True,
        "currency": "CNY",
    },
    "PF": {
        "name": "短纤",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 2,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 橡胶木材 ==========
    "RU": {
        "name": "天然橡胶",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "NR": {
        "name": "20号胶",
        "exchange": "INE",
        "multiplier": 10,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "SP": {
        "name": "纸浆",
        "exchange": "SHFE",
        "multiplier": 10,
        "price_tick": 2,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 油脂油料 ==========
    "M": {
        "name": "豆粕",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1.5,
        "night_trade": True,
        "currency": "CNY",
    },
    "Y": {
        "name": "豆油",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 2,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2.5,
        "night_trade": True,
        "currency": "CNY",
    },
    "P": {
        "name": "棕榈油",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 2,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2.5,
        "night_trade": True,
        "currency": "CNY",
    },
    "A": {
        "name": "豆一",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2,
        "night_trade": True,
        "currency": "CNY",
    },
    "B": {
        "name": "豆二",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1,
        "night_trade": True,
        "currency": "CNY",
    },
    "OI": {
        "name": "菜油",
        "exchange": "CZCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 2,
        "night_trade": True,
        "currency": "CNY",
    },
    "RM": {
        "name": "菜粕",
        "exchange": "CZCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.07,
        "commission_rate": 0,
        "commission_fixed": 1.5,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 农产品 ==========
    "C": {
        "name": "玉米",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 1.2,
        "night_trade": True,
        "currency": "CNY",
    },
    "CS": {
        "name": "玉米淀粉",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.07,
        "commission_rate": 0,
        "commission_fixed": 1.5,
        "night_trade": True,
        "currency": "CNY",
    },
    "JD": {
        "name": "鸡蛋",
        "exchange": "DCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.08,
        "commission_rate": 0.00015,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },
    "CF": {
        "name": "棉花",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.07,
        "commission_rate": 0,
        "commission_fixed": 4.3,
        "night_trade": True,
        "currency": "CNY",
    },
    "SR": {
        "name": "白糖",
        "exchange": "CZCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.07,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "AP": {
        "name": "苹果",
        "exchange": "CZCE",
        "multiplier": 10,
        "price_tick": 1,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 5,
        "night_trade": False,
        "currency": "CNY",
    },
    "CJ": {
        "name": "红枣",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": False,
        "currency": "CNY",
    },
    "PK": {
        "name": "花生",
        "exchange": "CZCE",
        "multiplier": 5,
        "price_tick": 2,
        "margin_rate": 0.08,
        "commission_rate": 0,
        "commission_fixed": 4,
        "night_trade": False,
        "currency": "CNY",
    },

    # ========== 生猪 ==========
    "LH": {
        "name": "生猪",
        "exchange": "DCE",
        "multiplier": 16,
        "price_tick": 5,
        "margin_rate": 0.10,
        "commission_rate": 0.0002,
        "commission_fixed": 0,
        "night_trade": False,
        "currency": "CNY",
    },

    # ========== 新能源 (GFEX) ==========
    "SI": {
        "name": "工业硅",
        "exchange": "GFEX",
        "multiplier": 5,
        "price_tick": 5,
        "margin_rate": 0.12,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },
    "LC": {
        "name": "碳酸锂",
        "exchange": "GFEX",
        "multiplier": 1,
        "price_tick": 50,
        "margin_rate": 0.15,
        "commission_rate": 0,
        "commission_fixed": 3,
        "night_trade": True,
        "currency": "CNY",
    },

    # ========== 航运 ==========
    "EC": {
        "name": "集运指数",
        "exchange": "INE",
        "multiplier": 50,
        "price_tick": 0.1,
        "margin_rate": 0.12,
        "commission_rate": 0.00005,
        "commission_fixed": 0,
        "night_trade": True,
        "currency": "CNY",
    },
}

# 策略参数默认值
DEFAULT_STRATEGY_PARAMS = {
    "brother2v5": {
        "sml_len": 10,
        "big_len": 40,
        "break_len": 40,
        "atr_len": 20,
        "adx_len": 14,
        "adx_thres": 25.0,
        "stop_n": 4.0,
        "capital_rate": 1.0,
        "risk_rate": 0.03,
    }
}

# 交易所信息
EXCHANGES = {
    "CFFEX": {"name": "中国金融期货交易所", "timezone": "Asia/Shanghai"},
    "SHFE": {"name": "上海期货交易所", "timezone": "Asia/Shanghai"},
    "DCE": {"name": "大连商品交易所", "timezone": "Asia/Shanghai"},
    "CZCE": {"name": "郑州商品交易所", "timezone": "Asia/Shanghai"},
    "INE": {"name": "上海国际能源交易中心", "timezone": "Asia/Shanghai"},
    "GFEX": {"name": "广州期货交易所", "timezone": "Asia/Shanghai"},
}

def get_instrument(symbol: str) -> dict:
    """获取品种配置"""
    return INSTRUMENTS.get(symbol.upper(), None)

def calculate_commission(symbol: str, price: float, volume: int) -> float:
    """计算手续费"""
    inst = get_instrument(symbol)
    if not inst:
        return 0

    if inst["commission_fixed"] > 0:
        return inst["commission_fixed"] * volume
    else:
        return price * inst["multiplier"] * volume * inst["commission_rate"]

def calculate_margin(symbol: str, price: float, volume: int) -> float:
    """计算保证金"""
    inst = get_instrument(symbol)
    if not inst:
        return 0
    return price * inst["multiplier"] * volume * inst["margin_rate"]

def calculate_pnl(symbol: str, entry_price: float, exit_price: float, volume: int, direction: int = 1) -> float:
    """
    计算盈亏
    direction: 1=多头, -1=空头
    """
    inst = get_instrument(symbol)
    if not inst:
        return 0
    return (exit_price - entry_price) * volume * inst["multiplier"] * direction
